# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- build
- deploy

image: docker:19.03.12

build:
  stage: build
  tags: ["docker-build"]
  before_script:
  - docker info
  script:
  - docker login -u "$HUB_USER" -p "$HUB_PASSWORD"
  - docker build -t "nicklesbread/seniordesign" .
  - docker image tag "nicklesbread/seniordesign:latest" "nicklesbread/seniordesign:$CI_PIPELINE_IID"
  - docker image tag "nicklesbread/seniordesign:latest" "nicklesbread/seniordesign:latest"
  - docker image push "nicklesbread/seniordesign:latest"
  - docker image push "nicklesbread/seniordesign:$CI_PIPELINE_IID"

# build_rabbit:
#   stage: build
#   tags: ["docker-build"]
#   script:
#     - docker login -u "$HUB_USER" -p "$HUB_PASSWORD"
#     - docker build -t "nicklesbread/rabbitmq-seniordesign" -f rabbit/Dockerfile.rabbit rabbit
#     - docker image tag "nicklesbread/rabbitmq-seniordesign:latest" "nicklesbread/rabbitmq-seniordesign:$CI_PIPELINE_IID"
#     - docker image tag "nicklesbread/rabbitmq-seniordesign:latest" "nicklesbread/rabbitmq-seniordesign:latest"
#     - docker image push "nicklesbread/rabbitmq-seniordesign:latest"
#     - docker image push "nicklesbread/rabbitmq-seniordesign:$CI_PIPELINE_IID"

deploy:
  stage: deploy
  tags: ["docker-build"]
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - find ./ecs_json -type f -exec sed -i -e "s/@DOCKER_TAG/${CI_PIPELINE_IID}/g" {} \;
    - aws ecs register-task-definition --cli-input-json file://ecs_json/task_def_bill_data_worker.json
    - aws ecs register-task-definition --cli-input-json file://ecs_json/task_def_flask_server.json
    - aws ecs register-task-definition --cli-input-json file://ecs_json/task_def_twitter_tweet_worker.json
    - aws ecs register-task-definition --cli-input-json file://ecs_json/task_def_twitter_user_worker.json
    - aws ecs update-service --cluster senior-design --service bill_data_worker --task-definition bill_data_worker
    - aws ecs update-service --cluster senior-design --service flask --task-definition flask-server
    - aws ecs update-service --cluster senior-design --service twitter_user_worker --task-definition twitter_user_worker
    - aws ecs update-service --cluster senior-design --service twitter_tweet_worker --task-definition twitter_tweet_worker



