# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- build

build:
  stage: build
  before_script:
  - docker info
  script:
  - echo "$CI_REGISTRY_IMAGE"
  - echo "$CI_PIPELINE_IID"
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  - docker build -t "$CI_REGISTRY_IMAGE" .
  - docker image tag "$CI_REGISTRY_IMAGE:latest" "$CI_REGISTRY_IMAGE/images:$CI_PIPELINE_IID"
  - docker image tag "$CI_REGISTRY_IMAGE:latest" "$CI_REGISTRY_IMAGE/images:latest"
  - docker image push "$CI_REGISTRY_IMAGE/images:latest"
  - docker image push "$CI_REGISTRY_IMAGE/images:$CI_PIPELINE_IID"
  #- docker push "$CI_REGISTRY_IMAGE:latest"
  #- docker push "$CI_REGISTRY_IMAGE:lmao"
#sast:
#  stage: test
#include:
#- template: Auto-DevOps.gitlab-ci.yml
