version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./app/:/app/
    - ../data/:/app/data
    ports:
      - 5000:5000
    environment:
      - cred_path=util/cred-user-1.json
      - SECRET_KEY=wowsuchsecret
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=bigpassword
    command: ['gunicorn', 'server:create_app()', '-b', '0.0.0.0:5000', '--reload']
    depends_on:
      - db
      - initializer

  initializer:
    build:
      context: .
      dockerfile: Dockerfile
    command: ['python3', 'initializer.py']
    depends_on:
      - db

  db:
    image: library/mysql:8.0.26
    platform: linux/x86_64
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      db_url: mysql://mysql:mysql@db:3306/mysql
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    ports:
      - 3306:3306

  redis:
    image: redis:latest

  rabbit:
    image: rabbitmq:3.8
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=bigpassword

  celery_worker_long_1:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A server.tasks worker -l INFO --uid 1 --concurrency 1 -Q long_task
    volumes:
    - ./app/:/app/
    - ../data/:/app/data
    environment:
      - cred_path=util/cred-user-1.json
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=bigpassword
    depends_on:
      - rabbit

  celery_worker_long_2:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A server.tasks worker -l INFO --uid 1 --concurrency 1 -Q long_task
    volumes:
    - ./app/:/app/
    - ../data/:/app/data
    environment:
      - cred_path=util/cred-user-2.json
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=bigpassword
    depends_on:
      - rabbit

  celery_worker_short_1:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A server.tasks worker -l INFO --uid 1 --concurrency 1 -Q short_task
    volumes:
      - ./app/:/app/
      - ../data/:/app/data
    environment:
      - cred_path=util/cred-user-1.json
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=bigpassword
    depends_on:
      - rabbit

  celery_worker_short_2:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A server.tasks worker -l INFO --uid 1 --concurrency 1 -Q short_task
    volumes:
      - ./app/:/app/
      - ../data/:/app/data
    environment:
      - cred_path=util/cred-user-2.json
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=bigpassword
    depends_on:
      - rabbit

volumes:
  mysql_data: