"""Remove FK
Revision ID: 006953af2b83
Revises: 193e0ad89152
Create Date: 2021-10-12 22:13:51.452416
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic
revision = '006953af2b83'
down_revision = '193e0ad89152'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bills', 'summary',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(length=16000000),
               existing_nullable=True)
    op.drop_constraint('bills_ibfk_1', 'bills', type_='foreignkey')
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('bills_ibfk_1', 'bills', 'congress_member_data', ['sponsor_id'], ['propublica_id'])
    op.alter_column('bills', 'summary',
               existing_type=sa.Text(length=16000000),
               type_=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    # ### end Alembic commands ###