"""Increasing field size
Revision ID: 0bd621b524cf
Revises: 237857d35dd9
Create Date: 2022-01-24 14:36:51.942318
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic
revision = '0bd621b524cf'
down_revision = '237857d35dd9'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('search_phrases', 'search_phrase',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('search_phrases', 'search_phrase',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               existing_nullable=False)
    # ### end Alembic commands ###