"""Allowing null on some fields
Revision ID: 0ef19d940745
Revises: 9276cb1f4213
Create Date: 2021-12-04 16:27:36.405122
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic
revision = '0ef19d940745'
down_revision = '9276cb1f4213'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bills', 'bill_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=8),
               nullable=True)
    op.alter_column('bills', 'number',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               nullable=True)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bills', 'number',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               nullable=False)
    op.alter_column('bills', 'bill_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=8),
               nullable=False)
    # ### end Alembic commands ###