"""Initial Tables
Revision ID: 10a71a8f08ec
Revises: 
Create Date: 2021-09-28 17:22:49.443939
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic
revision = '10a71a8f08ec'
down_revision = None
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_phrases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_phrase', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tweets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('author_id', sa.String(length=32), nullable=False),
    sa.Column('inserted_time', sa.DateTime(), nullable=False),
    sa.Column('time_tweeted', sa.DateTime(), nullable=False),
    sa.Column('text', sa.String(length=1024), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('lang', sa.String(length=8), nullable=True),
    sa.Column('reply', sa.Boolean(), nullable=False),
    sa.Column('reply_to_id', sa.String(length=32), nullable=True),
    sa.Column('retweets', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('replies', sa.Integer(), nullable=False),
    sa.Column('quote_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('user_email', sa.String(length=64), nullable=False),
    sa.Column('user_key_hash', sa.String(length=256), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('user_key_hash'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tweet_to_search',
    sa.Column('tweet_id', sa.String(length=32), nullable=True),
    sa.Column('phrase_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['phrase_id'], ['search_phrases.id'], ),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.id'], )
    )
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweet_to_search')
    op.drop_table('users')
    op.drop_table('tweets')
    op.drop_table('search_phrases')
    # ### end Alembic commands ###