"""update committees
Revision ID: 193e0ad89152
Revises: 79c634d7e724
Create Date: 2021-10-11 22:45:13.938776
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic
revision = '193e0ad89152'
down_revision = '79c634d7e724'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ##
    op.add_column('bills', sa.Column('sponsor_party', sa.String(length=16), nullable=True))
    op.alter_column('bills', 'committees',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bills', 'committees',
               existing_type=sa.String(length=128),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.drop_column('bills', 'sponsor_party')
    # ### end Alembic commands ###