"""Updating bill search phrases
Revision ID: 237857d35dd9
Revises: a6523b5da9f8
Create Date: 2022-01-23 17:32:12.912631
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic
revision = '237857d35dd9'
down_revision = 'a6523b5da9f8'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_to_search',
    sa.Column('bill_id', sa.String(length=16), nullable=True),
    sa.Column('phrase_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.bill_id'], ),
    sa.ForeignKeyConstraint(['phrase_id'], ['search_phrases.id'], )
    )
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill_to_search')
    # ### end Alembic commands ###