"""Adding user table
Revision ID: 32eb1351efab
Revises: 10a71a8f08ec
Create Date: 2021-09-30 21:03:08.160155
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic
revision = '32eb1351efab'
down_revision = '10a71a8f08ec'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('following_count', sa.Integer(), nullable=False),
    sa.Column('tweet_count', sa.Integer(), nullable=False),
    sa.Column('listed_count', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('protected', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('inserted_time', sa.DateTime(), nullable=False),
    sa.Column('account_created', sa.DateTime(), nullable=False),
    sa.Column('profile_image_url', sa.String(length=256), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitter_users')
    # ### end Alembic commands ###