"""Changing strings to dates
Revision ID: 49a19a0bb80a
Revises: bc0869fcd418
Create Date: 2022-01-26 18:41:13.031049
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic
revision = '49a19a0bb80a'
down_revision = 'bc0869fcd418'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bills', 'introduced_date',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('bills', 'last_vote',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('bills', 'house_passage',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('bills', 'senate_passage',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('bills', 'enacted',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('bills', 'vetoed',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               type_=sa.Date(),
               existing_nullable=True)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bills', 'vetoed',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               existing_nullable=True)
    op.alter_column('bills', 'enacted',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               existing_nullable=True)
    op.alter_column('bills', 'senate_passage',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               existing_nullable=True)
    op.alter_column('bills', 'house_passage',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               existing_nullable=True)
    op.alter_column('bills', 'last_vote',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               existing_nullable=True)
    op.alter_column('bills', 'introduced_date',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               existing_nullable=True)
    # ### end Alembic commands ###