"""Congress Member Data
Revision ID: 4dabf9ad9a7b
Revises: 32eb1351efab
Create Date: 2021-10-07 14:05:36.913457
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic
revision = '4dabf9ad9a7b'
down_revision = '32eb1351efab'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('congress_member_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('propublica_id', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('middle_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('suffix', sa.String(length=16), nullable=True),
    sa.Column('date_of_birth', sa.String(length=32), nullable=True),
    sa.Column('gender', sa.String(length=2), nullable=True),
    sa.Column('party', sa.String(length=32), nullable=True),
    sa.Column('twitter_account', sa.String(length=128), nullable=True),
    sa.Column('facebook_account', sa.String(length=128), nullable=True),
    sa.Column('youtube_account', sa.String(length=128), nullable=True),
    sa.Column('govtrack_id', sa.Integer(), nullable=True),
    sa.Column('cspan_id', sa.Integer(), nullable=True),
    sa.Column('votesmart_id', sa.Integer(), nullable=True),
    sa.Column('icpsr_id', sa.Integer(), nullable=True),
    sa.Column('crp_id', sa.String(length=32), nullable=True),
    sa.Column('google_entity_id', sa.String(length=64), nullable=True),
    sa.Column('fec_canidate_id', sa.String(length=32), nullable=True),
    sa.Column('inserted_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('propublica_id')
    )
    op.create_table('congress_member_instance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('congress_member_id', sa.Integer(), nullable=True),
    sa.Column('congress', sa.Integer(), nullable=False),
    sa.Column('chamber', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('short_title', sa.String(length=16), nullable=True),
    sa.Column('leadership_role', sa.String(length=64), nullable=True),
    sa.Column('seniority', sa.String(length=8), nullable=True),
    sa.Column('next_election', sa.String(length=8), nullable=True),
    sa.Column('total_votes', sa.Integer(), nullable=True),
    sa.Column('missed_votes', sa.Integer(), nullable=True),
    sa.Column('total_present', sa.Integer(), nullable=True),
    sa.Column('senate_class', sa.String(length=16), nullable=True),
    sa.Column('senate_rank', sa.String(length=16), nullable=True),
    sa.Column('missed_votes_pct', sa.Float(), nullable=True),
    sa.Column('votes_with_party_pct', sa.Float(), nullable=True),
    sa.Column('votes_against_party_pct', sa.Float(), nullable=True),
    sa.Column('inserted_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['congress_member_id'], ['congress_member_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('congress_member_instance')
    op.drop_table('congress_member_data')
    # ### end Alembic commands ###