"""Adding unprocessed tweets
Revision ID: 5588f997182f
Revises: cfcf081f1fc4
Create Date: 2022-04-06 20:26:02.315754
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic
revision = '5588f997182f'
down_revision = 'cfcf081f1fc4'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unprocessed_tweets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tweet_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_unprocessed_tweets_tweet_id'), 'unprocessed_tweets', ['tweet_id'], unique=False)
    op.alter_column('bills', 'sentiment',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bills', 'sentiment',
               existing_type=sa.JSON(),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               existing_nullable=True)
    op.drop_index(op.f('ix_unprocessed_tweets_tweet_id'), table_name='unprocessed_tweets')
    op.drop_table('unprocessed_tweets')
    # ### end Alembic commands ###