"""Increasing column size
Revision ID: 57474e061f0f
Revises: b09fc1873142
Create Date: 2021-11-14 01:19:21.373516
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic
revision = '57474e061f0f'
down_revision = 'b09fc1873142'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bill_actions', 'action_type',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('bill_actions', 'description',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=4096),
               existing_nullable=True)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bill_actions', 'description',
               existing_type=sa.String(length=4096),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('bill_actions', 'action_type',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###