"""unnulling
Revision ID: 6e9cb256bc0d
Revises: 57474e061f0f
Create Date: 2021-11-14 12:40:17.088537
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic
revision = '6e9cb256bc0d'
down_revision = '57474e061f0f'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bill_actions', 'chamber',
               existing_type=mysql.VARCHAR(length=16),
               nullable=True)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bill_actions', 'chamber',
               existing_type=mysql.VARCHAR(length=16),
               nullable=False)
    # ### end Alembic commands ###