"""Adding bill subject
Revision ID: 79c634d7e724
Revises: db5baeb14bd0
Create Date: 2021-10-11 17:59:10.044783
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic
revision = '79c634d7e724'
down_revision = 'db5baeb14bd0'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('url_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subcommittee_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subcommittee_code', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_to_committee_code',
    sa.Column('bill_id', sa.String(length=16), nullable=True),
    sa.Column('committee_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.bill_id'], ),
    sa.ForeignKeyConstraint(['committee_code'], ['committee_codes.id'], )
    )
    op.create_table('bill_to_subcommittee_code',
    sa.Column('bill_id', sa.String(length=16), nullable=True),
    sa.Column('subcommittee_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.bill_id'], ),
    sa.ForeignKeyConstraint(['subcommittee_code'], ['subcommittee_codes.id'], )
    )
    op.create_table('bill_to_subject',
    sa.Column('bill_id', sa.String(length=16), nullable=True),
    sa.Column('subject', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.bill_id'], ),
    sa.ForeignKeyConstraint(['subject'], ['bill_subjects.id'], )
    )
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill_to_subject')
    op.drop_table('bill_to_subcommittee_code')
    op.drop_table('bill_to_committee_code')
    op.drop_table('subcommittee_codes')
    op.drop_table('bill_subjects')
    # ### end Alembic commands ###