"""updates to tasks
Revision ID: 924ea299e825
Revises: 1ef16633796a
Create Date: 2022-02-15 23:15:44.954111
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic
revision = '924ea299e825'
down_revision = '1ef16633796a'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_errors', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256),
               type_=sa.String(length=4096),
               existing_nullable=False)
    op.add_column('tasks', sa.Column('type', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'type')
    op.alter_column('task_errors', 'description',
               existing_type=sa.String(length=4096),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256),
               existing_nullable=False)
    # ### end Alembic commands ###