"""Adding full_text column
Revision ID: 9276cb1f4213
Revises: 6e9cb256bc0d
Create Date: 2021-11-28 20:35:09.314740
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic
revision = '9276cb1f4213'
down_revision = '6e9cb256bc0d'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill_verions', sa.Column('full_text', mysql.LONGTEXT(), nullable=True))
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bill_verions', 'full_text')
    # ### end Alembic commands ###