"""Adding tasks table
Revision ID: b678aff4ac01
Revises: 006953af2b83
Create Date: 2021-10-15 16:53:01.310853
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic
revision = 'b678aff4ac01'
down_revision = '006953af2b83'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('launched_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['launched_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('bills', 'summary',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(length=16000000),
               existing_nullable=True)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bills', 'summary',
               existing_type=sa.Text(length=16000000),
               type_=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    op.drop_table('tasks')
    # ### end Alembic commands ###