"""Adding autoincrement
Revision ID: bf46562b137d
Revises: 5588f997182f
Create Date: 2022-04-14 22:17:26.750726
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic
revision = 'bf46562b137d'
down_revision = '5588f997182f'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unprocessed_tweets', 'id',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index('ix_unprocessed_tweets_tweet_id', table_name='unprocessed_tweets')
    op.create_index(op.f('ix_unprocessed_tweets_tweet_id'), 'unprocessed_tweets', ['tweet_id'], unique=True)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unprocessed_tweets_tweet_id'), table_name='unprocessed_tweets')
    op.create_index('ix_unprocessed_tweets_tweet_id', 'unprocessed_tweets', ['tweet_id'], unique=False)
    op.alter_column('unprocessed_tweets', 'id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###