"""Adding sentiment fields
Revision ID: d59e0702753e
Revises: f8288e10a497
Create Date: 2022-01-21 18:58:13.354180
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic
revision = 'd59e0702753e'
down_revision = 'f8288e10a497'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('sentiment', sa.Float(), nullable=True))
    op.add_column('tweets', sa.Column('seniment', sa.Float(), nullable=True))
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweets', 'seniment')
    op.drop_column('bills', 'sentiment')
    # ### end Alembic commands ###