"""Adding new task structure
Revision ID: d7a7e9a514a8
Revises: a4b8e9bcac89
Create Date: 2022-02-15 22:22:14.586215
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic
revision = 'd7a7e9a514a8'
down_revision = 'a4b8e9bcac89'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_errors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Boolean(), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.Column('launched_by_id', sa.Integer(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['launched_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('task_errors')
    # ### end Alembic commands ###