"""Adding bill data
Revision ID: db5baeb14bd0
Revises: baa1d5dc0dff
Create Date: 2021-10-11 17:17:47.161748
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic
revision = 'db5baeb14bd0'
down_revision = 'baa1d5dc0dff'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('committee_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('committee_code', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subcommitee_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subcommittee_code', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bills',
    sa.Column('bill_id', sa.String(length=16), nullable=False),
    sa.Column('congress', sa.Integer(), nullable=False),
    sa.Column('bill_slug', sa.String(length=16), nullable=False),
    sa.Column('bill_type', sa.String(length=8), nullable=False),
    sa.Column('number', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=2048), nullable=True),
    sa.Column('short_title', sa.String(length=1024), nullable=True),
    sa.Column('sponsor_id', sa.String(length=16), nullable=True),
    sa.Column('gpo_pdf_uri', sa.String(length=1024), nullable=True),
    sa.Column('congressdotgov_url', sa.String(length=1024), nullable=True),
    sa.Column('govtrack_url', sa.String(length=1024), nullable=True),
    sa.Column('introduced_date', sa.String(length=32), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('last_vote', sa.String(length=32), nullable=True),
    sa.Column('house_passage', sa.String(length=32), nullable=True),
    sa.Column('senate_passage', sa.String(length=32), nullable=True),
    sa.Column('enacted', sa.String(length=32), nullable=True),
    sa.Column('vetoed', sa.String(length=32), nullable=True),
    sa.Column('cosponsors', sa.Integer(), nullable=True),
    sa.Column('dem_cosponsors', sa.Integer(), nullable=True),
    sa.Column('rep_cosponsors', sa.Integer(), nullable=True),
    sa.Column('committees', sa.Integer(), nullable=True),
    sa.Column('primary_subject', sa.String(length=1024), nullable=True),
    sa.Column('summary', sa.String(length=4096), nullable=True),
    sa.Column('summary_short', sa.String(length=2048), nullable=True),
    sa.Column('latest_major_action_date', sa.String(length=32), nullable=True),
    sa.Column('latest_major_action', sa.String(length=2048), nullable=True),
    sa.Column('inserted_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sponsor_id'], ['congress_member_data.propublica_id'], ),
    sa.PrimaryKeyConstraint('bill_id'),
    sa.UniqueConstraint('bill_id')
    )
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bills')
    op.drop_table('subcommitee_codes')
    op.drop_table('committee_codes')
    # ### end Alembic commands ###