"""Adding lock field
Revision ID: eb8c090680d0
Revises: 924ea299e825
Create Date: 2022-02-23 18:36:55.514456
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic
revision = 'eb8c090680d0'
down_revision = '924ea299e825'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('key_rate_limit', sa.Column('locked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('key_rate_limit', 'locked')
    # ### end Alembic commands ###