"""removing keyword table
Revision ID: ebb5a3514c30
Revises: 0bd621b524cf
Create Date: 2022-01-24 21:34:39.396668
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic
revision = 'ebb5a3514c30'
down_revision = '0bd621b524cf'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill_key_words')
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_key_words',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('phrase', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('bill', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16), nullable=True),
    sa.ForeignKeyConstraint(['bill'], ['bills.bill_id'], name='bill_key_words_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###