apiVersion: batch/v1
kind: CronJob
metadata:
  name: sd-recent-bills-cron
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: "OnFailure"
          containers:
            - name: sd-recent-bills-cron
              image: nicklesbread/seniordesign:@DOCKER_TAG
              imagePullPolicy: "IfNotPresent"
              command: ['python3', 'cron_runner.py', 'get_recent_bills']
              env:
                - name: connection_string
                  valueFrom:
                    secretKeyRef:
                      name: system
                      key: connection_string
                - name: celery_connection_string
                  valueFrom:
                    secretKeyRef:
                      name: system
                      key: celery_connection_string
                - name: CELERY_BROKER_URL
                  valueFrom:
                    secretKeyRef:
                      name: rabbit
                      key: broker_url
          imagePullSecrets:
            - name: docker-hub-auth