apiVersion: apps/v1
kind: Deployment
metadata:
  name: sd-celery-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sd-celery-ml
  template:
    metadata:
      labels:
        app: sd-celery-ml
    spec:
      containers:
        - name: sd-celery-ml
          image: nicklesbread/seniordesign:@DOCKER_TAG
          imagePullPolicy: "IfNotPresent"
          command: ['celery', '-A', 'tasks.task_ml_initializer', 'worker', '-l', 'INFO', '--concurrency', '2', '-Q', 'ml_tasks', '--pool', 'threads', '--without-gossip', '--without-mingle']
          env:
            - name: connection_string
              valueFrom:
                secretKeyRef:
                  name: system
                  key: connection_string
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbit
                  key: user
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbit
                  key: password
            - name: celery_connection_string
              valueFrom:
                secretKeyRef:
                  name: system
                  key: celery_connection_string
            - name: RABBITMQ_HOST
              value: rabbit
            - name: RABBITMQ_PORT
              value: "5672"
      imagePullSecrets:
        - name: docker-hub-auth