apiVersion: apps/v1
kind: Deployment
metadata:
  name: sd-celery-twitter-tweet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sd-celery-twitter-tweet
  template:
    metadata:
      labels:
        app: sd-celery-twitter-tweet
    spec:
      containers:
        - name: sd-celery-twitter-tweet
          image: nicklesbread/seniordesign:@DOCKER_TAG
          imagePullPolicy: "IfNotPresent"
          command: ['celery', '-A', 'tasks.task_initializer', 'worker', '-l', 'INFO', '--concurrency', '2', '-Q', 'twitter_archive', '--uid', '1', '--without-gossip', '--without-mingle']
          env:
            - name: connection_string
              valueFrom:
                secretKeyRef:
                  name: system
                  key: connection_string
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbit
                  key: user
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbit
                  key: password
            - name: celery_connection_string
              valueFrom:
                secretKeyRef:
                  name: system
                  key: celery_connection_string
            - name: twitter_api_url
              valueFrom:
                secretKeyRef:
                  name: twitter
                  key: twitter_api_url
            - name: twitter_bearer_token_1
              valueFrom:
                secretKeyRef:
                  name: twitter
                  key: twitter_bearer_token_1
            - name: twitter_bearer_token_2
              valueFrom:
                secretKeyRef:
                  name: twitter
                  key: twitter_bearer_token_2
            - name: twitter_bearer_token_3
              valueFrom:
                secretKeyRef:
                  name: twitter
                  key: twitter_bearer_token_3
            - name: twitter_bearer_token_4
              valueFrom:
                secretKeyRef:
                  name: twitter
                  key: twitter_bearer_token_4
            - name: twitter_bearer_token_5
              valueFrom:
                secretKeyRef:
                  name: twitter
                  key: twitter_bearer_token_5
            - name: RABBITMQ_HOST
              value: rabbit
            - name: RABBITMQ_PORT
              value: 5672
      imagePullSecrets:
        - name: docker-hub-auth