apiVersion: v1
kind: Service
metadata:
  name: sd-maria
  labels:
    app: sd-maria
spec:
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: sd-maria