kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sd-maria-pv-claim
  labels:
    app: sd-maria
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sd-rabbit-pv-claim
  labels:
    app: sd-rabbit
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi